#!/usr/bin/env bash

BRANCH=$(cat .branchdata)
if [ -z "$BRANCH" ]
then
	echo "Please run the ./new-feature script first."
else
	if git checkout main ; then
		if git branch -D "$BRANCH" ; then
			rm .branchdata
		fi
	fi
fi
