#!/usr/bin/env bash

if [ -z "$1" ]
then
	echo "Please give the feature a name!"
else
	git checkout main
	if git pull origin main; then
		git checkout -b $1
		echo $1 > .branchdata
	else
		echo "Failed to pull changes from github!"
	fi
fi
